version: '3'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=finance
    ports:
      - "5432:5432"
    volumes:
      - personal_finance:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - "7000:7000"
    environment:
      - postgres_URI=database
      - postgres_USER=postgres
      - postgres_PWD=docker
      - postgres_DB=finance
    volumes:
      - ./server:/usr/src/server/
      - /usr/src/server/node_modules
    links:
      - database
    depends_on:
      - database
  client:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/client/node_modules
      - ./client:/usr/src/client/
volumes:
  personal_finance:
    
